#!/bin/env bash
#===============================================================================
#
#          FILE: buildaquariosmod
#
#         USAGE: ./buildaquariosmod device
#
#   DESCRIPTION: Android build script.
#
#       OPTIONS:
#  REQUIREMENTS: Android source, android-sdk, repo, git, bash, tee, time
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Mike Redd (MikereDD), mikeredd@mobileinfern.us
#  ORGANIZATION: Dumb Terminal Team
#       CREATED: 01/23/2014 12:53
#      REVISION: 05/03/2019 03:14
#===============================================================================

#shopt -s -o nounset

# Colorize and add text parameters
red=$(tput setaf 1) # red
grn=$(tput setaf 2) # green
cya=$(tput setaf 6) # cyan
txtbld=$(tput bold) # Bold
bldred=${txtbld}$(tput setaf 1) # red
bldgrn=${txtbld}$(tput setaf 2) # green
bldblu=${txtbld}$(tput setaf 4) # blue
bldcya=${txtbld}$(tput setaf 6) # cyan
txtrst=$(tput sgr0) # Reset


#Variable declarations
SCRIPT="buildscript"
VERSION="1.9"
DTEVER=`date +%Y%m%d`
LOGS="${PWD}/../build_logs"
HEAD=`which head`
REPO=`which repo`
DEVICE="$1"

# Time of build startup
res1=$(date +%s.%N)

echo
echo -e " ${red}Building ${bldcya}AquariOS-MOD-$DTEVER ${txtrst}";
echo
echo
echo -e ${bldcya}'       .oo .oPYo.  o    o      .oo '
echo -e '      .P 8 8    8  8    8     .P 8 '
echo -e '     .P  8 8    8  8    8    .P  8 '
echo -e '    oPooo8 8  d.8  8    8   oPooo8 '
echo -e '   .P    8 8  `b8. 8    8  .P    8 '
echo -e '  .P     8 `YooP.P `YooP. .P     8 '
echo -e ' ..:::::..:....:.::.....:..:::::.. '
echo -e ' ::::::::::::::::::::::::::::::::: '
echo -e ' ::::::::::::::::::::::::::::::::: '${txtrst}
echo
echo -e " ${grn}$SCRIPT ${txtrst}... Ver:${cya}$VERSION ${txtrst} "
echo

# Create build_logs directory
if [ ! -d "$LOGS" ]; then
    echo
    echo -e " ${bldgrn}Creating build_logs directory${txtrst}..."
    mkdir -p $LOGS
    echo
else
    # remove old build logs
    echo -e " ${bldred}Removing old build logs${txtrst}..."
    rm -rf $LOGS/*
    echo -e " ${bldred}Logs removed${txtrst}..."
    echo
fi

# setup environment
echo -e " ${bldred}Setting up build environment ${txtrst}"
. build/envsetup.sh

# lunch device
echo
echo -e "${bldred}Lunching your device ${txtrst}"
breakfast "$DEVICE-userdebug";

echo
echo -e " ${bldred}Starting AquariOS build for $DEVICE ${txtrst}"
echo
echo -e " ${bldblu}...${txtrst} device=${bldred}$DEVICE${txtrst} ${bldblu}...${txtrst} ${bldblu}...${txtrst} threads=${bldred}32${txtrst} ${bldblu}...${txtrst} "
echo

# start build
# log builds by date + time
time mka aquarios 2>&1 | tee $LOGS/aquariosmod_$DEVICE-$(date '+%H.%m.%S-%h.%d').log;
echo

# finished? get elapsed time
res2=$(date +%s.%N)
echo -e " ${bldgrn}Total time elapsed: ${txtrst}${grn}$(echo "($res2 - $res1) / 60"|bc ) minutes ($(echo "$res2 - $res1"|bc ) seconds) ${txtrst}"
echo

# email build status
echo sending build status
sh $HOME/bin/email-push-to-pcloud-mod.sh
echo email sent
echo
